import type { Metadata } from "next";
// import { Geist, Geist_Mono, Nunito_Sans } from "next/font/google";
import "./fonts.css";
import "./globals.css";
import { Providers } from "@/providers";

// const geistSans = Geist({
// 	variable: "--font-geist-sans",
// 	subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
// 	variable: "--font-geist-mono",
// 	subsets: ["latin"],
// });

// const nunitoSans = Nunito_Sans({
// 	variable: "--font-nunito-sans",
// 	subsets: ["latin"],
// });

// const nunitoMono = Nunito_Sans({
// 	variable: "--font-nunito-mono",
// 	subsets: ["latin"],
// });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			{/* <head>
				<link
					href="https://fonts.cdnfonts.com/css/futura-pt"
					rel="stylesheet"
				/>
			</head> */}
			<body className={`antialiased`}>
				<Providers>{children}</Providers>
			</body>
		</html>
	);
}
