account_id = "8538ee8a1b128c2aecf17e5d9f495b40"
name = "hydrogen-storefront-sense"
main = "build/server/index.js"

compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "build/client"
binding = "ASSETS"

[observability]
enabled = true


