name = "hydrogen-storefront-sense"
main = "dist/server/index.js"
compatibility_date = "2024-11-18"
compatibility_flags = ["nodejs_compat"]

[assets]
# directory = "dist/client"
# binding = "ASSETS"

# [vars]
# Add your environment variables here. 
# These should match the keys in your .env file.
# PUBLIC_STORE_DOMAIN = "..."
# PUBLIC_STOREFRONT_API_TOKEN = "..."
# SESSION_SECRET = "..."
